# Stage 1: Build Nginx
FROM debian:latest AS build-nginx

# Install dependencies
RUN apt-get update
RUN apt-get install -y cmake libc-ares-dev g++ libre2-dev mercurial curl perl git libssl-dev zlib1g-dev libpcre3 libpcre3-dev
RUN apt-get install -y perl-modules cpanminus
RUN cpan Crypt::Misc
RUN cpan Net::SSLeay
RUN cpan IO::Socket::SSL

# Clone nginx repository
RUN hg clone http://hg.nginx.org/nginx/ /nginx
WORKDIR /nginx

# Clone nginx-nacos-upstream repository
RUN git clone https://github.com/nacos-group/nginx-nacos-upstream /nginx-nacos-upstream

# Ensure the /nginx/modules directory exists
RUN mkdir -p /nginx/modules

# Copy nginx-nacos-upstream to the same level as auto/configure
RUN cp -r /nginx-nacos-upstream/modules/nacos /nginx/modules/nacos
RUN cp -r /nginx-nacos-upstream/modules/auxiliary /nginx/modules/auxiliary

# Build nginx with additional modules
RUN ./auto/configure --with-compat --with-debug --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-http_stub_status_module \
                   --add-module=/nginx/modules/auxiliary --add-module=/nginx/modules/nacos --prefix=.. \
                   --conf-path=conf/my.conf --error-log-path=objs/logs/error.log --pid-path=objs/logs/nginx.pid \
                   --lock-path=objs/logs/nginx.lock --http-log-path=objs/logs/access.log && \
    make -j 4

# Copy all object files
RUN find /nginx/objs -name '*.o' -exec cp {} /artifacts/ \;