name: nginx-otel-module-check
run-name: ${{ github.actor }} is triggering pipeline
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ngx_otel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build images
        run: |
          ls -alth
          docker build -t ssr:latest . -f Dockerfile_otel
          docker tag ssr:latest docker.io/cdfng/nginx:ngx_otel
          docker push docker.io/cdfng/nginx:ngx_otel
  ngx_nacos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build images
        run: |
          ls -alth
          docker build -t ssr:latest . -f Dockerfile_nacos
          docker tag ssr:latest docker.io/cdfng/nginx:ngx_nacos
          docker push docker.io/cdfng/nginx:ngx_nacos
  build_nginx:
    runs-on: ubuntu-latest
    needs:
      - ngx_otel
      - ngx_nacos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build images
        run: |
          ls -alth
          docker build -t ssr:latest . -f Dockerfile
          docker tag ssr:latest docker.io/cdfng/nginx:zwk
          docker push docker.io/cdfng/nginx:zwk